"""empty message

Revision ID: 3d4f4f9bf703
Revises: 
Create Date: 2019-04-25 12:17:29.681356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4f4f9bf703'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reddit_id', sa.String(length=7), nullable=True),
    sa.Column('reddit_link', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=23), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reddit_id'),
    sa.UniqueConstraint('reddit_link')
    )
    op.create_index(op.f('ix_comment_body'), 'comment', ['body'], unique=False)
    op.create_index(op.f('ix_comment_created_at'), 'comment', ['created_at'], unique=False)
    op.create_table('holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('avg_entry_price', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('cost_basis', sa.Float(), nullable=True),
    sa.Column('unrealized_pl', sa.Float(), nullable=True),
    sa.Column('unrealized_plpc', sa.Float(), nullable=True),
    sa.Column('unrealized_intraday_pl', sa.Float(), nullable=True),
    sa.Column('unrealized_intraday_plpc', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('lastday_price', sa.Float(), nullable=True),
    sa.Column('change_today', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holding_symbol'), 'holding', ['symbol'], unique=False)
    op.create_table('mention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(length=7), nullable=True),
    sa.Column('symbol', sa.String(length=8), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('avg_sentiment', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['symbol'], ['holding.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mention_created_at'), 'mention', ['created_at'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alpaca_id', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=8), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('filled_qty', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('time_in_force', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('filled_avg_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['holding.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_alpaca_id'), 'transaction', ['alpaca_id'], unique=False)
    op.create_index(op.f('ix_transaction_created_at'), 'transaction', ['created_at'], unique=False)
    op.create_index(op.f('ix_transaction_filled_at'), 'transaction', ['filled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_filled_at'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_created_at'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_alpaca_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_mention_created_at'), table_name='mention')
    op.drop_table('mention')
    op.drop_index(op.f('ix_holding_symbol'), table_name='holding')
    op.drop_table('holding')
    op.drop_index(op.f('ix_comment_created_at'), table_name='comment')
    op.drop_index(op.f('ix_comment_body'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
