"""adds status to Holding model

Revision ID: c836197e5dc2
Revises: f076f8c62b0a
Create Date: 2019-04-29 13:27:14.884658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c836197e5dc2'
down_revision = 'f076f8c62b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holding', sa.Column('status', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_holding_status'), 'holding', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holding_status'), table_name='holding')
    op.drop_column('holding', 'status')
    # ### end Alembic commands ###
