"""adds updated_at to AlpacaAccount table

Revision ID: f076f8c62b0a
Revises: 37173e276aa3
Create Date: 2019-04-26 17:39:15.383897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f076f8c62b0a'
down_revision = '37173e276aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alpaca_account', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alpaca_account', 'updated_at')
    # ### end Alembic commands ###
